### ISSUE TITLE
Solr 3.6

### ISSUE THREAD

**Issue by BradStephens** [LucidWorks/auto-phrase-tokenfilter#9]
Any chance of this working on Solr 3.6? I compiled it and it's loading when I start Solr, but if I add a com.lucidworks.analysis.AutoPhrasingTokenFilterFactor to a fieldType in my schema, I get the following error on solr/tomcat startup:

`SEVERE: java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:398)
        at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:429)
        at org.apache.solr.util.plugin.AbstractPluginLoader.create(AbstractPluginLoader.java:83)
        at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:140)
        at org.apache.solr.schema.IndexSchema.readAnalyzer(IndexSchema.java:1017)
        at org.apache.solr.schema.IndexSchema.access$100(IndexSchema.java:60)
        at org.apache.solr.schema.IndexSchema$1.create(IndexSchema.java:453)
        at org.apache.solr.schema.IndexSchema$1.create(IndexSchema.java:433)
        at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:140)
        at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:490)
        at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:123)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:478)
        at org.apache.solr.core.CoreContainer.load(CoreContainer.java:332)
        at org.apache.solr.core.CoreContainer.load(CoreContainer.java:216)
        at org.apache.solr.core.CoreContainer$Initializer.initialize(CoreContainer.java:161)
        at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:96)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:295)
        at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(ApplicationFilterConfig.java:424)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:115)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4076)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4730)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
        at org.apache.catalina.core.StandardService.start(StandardService.java:525)
        at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
    Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.ResourceLoaderAware
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 57 more`

**Comment by github4dheeraj** [comment]
I am also getting the same error with Solr cloud 7.3.0
1. I upgraded this as a maven project with 7.3.0 dependencies and fixed compilation issues.
2. Added the jar to ${SOLR_HOME}/server/lib dir
3. Modified solrconfig.xml and managed-schema as per the given documentation.
4. trying to create solr collection and getting the same issue.

Appreciate your help

**Comment by github4dheeraj** [comment]
Finally worked
I had 3 nodes for solr cloud. I had to put the jar in each node inside a lib folder and then added 
`<lib dir="./lib/" regex=".*\.jar" />` in solrConfig.xml
