### ISSUE TITLE
Error : No suitable constructor found for WhitespaceTokenizer(StringReader) when compile with solr 5.1.0

### ISSUE THREAD

**Issue by hoangvu88** [LucidWorks/auto-phrase-tokenfilter#10]
When i compile with solr 5.1.0, javac throw this error:

[javac] /Java/auto-phrase-tokenfilter/src/main/java/com/lucidworks/analysis/AutoPhrasingQParserPlugin.java:113: error: no suitable constructor found for WhitespaceTokenizer(StringReader)
    [javac]     WhitespaceTokenizer wt = new WhitespaceTokenizer(  new StringReader( input ));
    [javac]                              ^
    [javac]     constructor WhitespaceTokenizer.WhitespaceTokenizer(AttributeFactory) is not applicable
    [javac](actual argument StringReader cannot be converted to AttributeFactory by method invocation conversion)
    [javac]     constructor WhitespaceTokenizer.WhitespaceTokenizer() is not applicable
    [javac](actual and formal argument lists differ in length)
    [javac] Note: /Java/auto-phrase-tokenfilter/src/main/java/com/lucidworks/analysis/AutoPhrasingTokenFilter.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

**Comment by hoangvu88** [comment]
I founded that this issue has been resolved, sorry :)
